Week1
Lidemy/mentor-program-5th-shes830501 pull request #2
Opened 2021-04-14 18:08 UTC by shes830501

2021-04-16 15:07 UTC, cwc329 requested changes

2021-04-16 15:07 UTC, cwc329 commented on homeworks/week1/hw1.md
> +>**`homworks > week1 > hw1.md`**
這是什麼指令嗎？

2021-04-16 15:07 UTC, cwc329 commented on homeworks/week1/hw1.md
> +>**File changed > `git commit -am "update hw1"` > branch - week1**
local commit 之後就好了嗎？

2021-04-16 15:07 UTC, cwc329 commented on homeworks/week1/hw3.md
> +5. **建立**名為 afu.js 的**檔案**： ```touch afu.js```
作業完整不過稍簡短。

2021-04-16 15:07 UTC, cwc329 commented on homeworks/week1/hw4.md
> +使用 Git 備份檔案，可以清楚地記錄每個檔案是誰在何時加進來、何時被修改或刪除。
備份檔案？
這好像不是 git 的目的喔

2021-04-16 15:07 UTC, cwc329 commented on homeworks/week1/hw4.md
> +```
整段的操作會在哪個資料夾呢？

2021-04-16 15:07 UTC, cwc329 commented on homeworks/week1/hw4.md
> +git remote add origin https://github.com/shes830501/joke.git
如果今天有其他人也用這段指令，會有什麼問題嗎？

2021-04-16 15:07 UTC, cwc329 commented on homeworks/week1/hw4.md
> +* 最後 ```git push origin main(branch name)```
如果要表示這是一個會變動的數值，可以用類似這樣的方式 <branchName> 或者其他方式，直接把 'main' 打出來會有點影響閱讀。

2021-04-16 15:07 UTC, cwc329 commented on homeworks/week1/hw4.md
> +11. 若之後笑話有修改，照著上述 **git 3 步驟**操作即可
哪三個步驟呢？

2021-04-16 15:07 UTC, cwc329 commented on homeworks/week1/hw4.md
> +12. 如果看到 GitHub上 有好笑的笑話，可以在別人的 respository 頁面右上角點選**綠色按鈕** ```↓Code```，將網址複製後，打開 Git Bash 輸入```git clone (網址)```，便完成下載了
那如果你想要用他的笑話為基礎改逼成你自己的版本，那要怎麼做比較好呢？

2021-04-16 15:07 UTC, cwc329 commented on homeworks/week1/hw1.md
> +
作業改好之後要怎麼做呢？

2021-04-16 15:07 UTC, cwc329 commented on homeworks/week1/hw5.md
> +開發者還必須使用多種程式工具編寫**乾淨**、**可移植**、具有**良好文檔支持**的代碼來創建或更新 Web 應用。
這邊指的是後端開發者還是所有開發者？
另外可移植的定義是怎樣呢？

2021-04-16 15:07 UTC, cwc329 commented on homeworks/week1/hw5.md
> +2. 瀏覽器底端的 **Hardware** 將指令經由上層的 **Operating System** ，再傳送至最頂端的**Web Browser**
瀏覽器就我了解是一個應用程式，怎麼會有 hardware？
另外上層和頂端這樣寫會讓我不太知道哪個層級比較高。

2021-04-16 15:07 UTC, cwc329 commented on homeworks/week1/hw5.md
> +3. Web Browser 透過 **Network Interface Controller(NIC)**，傳送 *HTTP* 形式的 **Request** 到 **Google Server**，再存在 **Google Database**
request 通常不會存在 database。
database 通常會儲存想要長期保存的資料，request 通常不是會想要長期儲存的資料。

2021-04-16 15:07 UTC, cwc329 commented on homeworks/week1/hw5.md
> +2. ```exit```: 關閉視窗
這其實不只有關閉視窗的功能，
嚴格來說是離開當前的 session。

2021-04-16 15:13 UTC, cwc329 commented
恭喜完成作業。
git 的部分可能需要再多了解一些，這個對於未來會很有幫助。
關於 review，看你是要在這個 PR 修好之後再 merge，或者自己 merge 之後再開一個 branch 訂正也可以。

2021-04-19 12:04 UTC, shes830501 commented on homeworks/week1/hw1.md
> +>**`homworks > week1 > hw1.md`**
homeworks, week1都是資料夾

2021-05-04 10:25 UTC, merged